In [1]:
import pandas as pd
import numpy as np

In this module we’ll be looking at data from the New York City tree census: 

https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/uvpi-gqnh

This data is collected by volunteers across the city, and is meant to catalog information about every single tree in the city.

Build a dash app for a arborist studying the health of various tree species (as defined by the variable ‘spc_common’) across each borough (defined by the variable ‘borough’). This arborist would like to answer the following two questions for each species and in each borough:

#### 1. What proportion of trees are in good, fair, or poor health according to the ‘health’ variable?

In [2]:
soql_url_1 = ('https://data.cityofnewyork.us/resource/nwxe-4ae8.json?' +\
        '$select=health,count(tree_id)' +\
        '&$group=health').replace(' ', '%20')

soql_trees_1 = pd.read_json(soql_url_1)

soql_trees_1

  health  count_tree_id
0   Fair          96504
1   Good         528850
2   Poor          26818
3    NaN          31616

#### 2. Are stewards (steward activity measured by the ‘steward’ variable) having an impact on the health of trees?

In [4]:
soql_url_2 = ('https://data.cityofnewyork.us/resource/nwxe-4ae8.json?' +\
        '$select=health,steward,count(tree_id)' +\
        '&$group=health,steward').replace(' ', '%20')

soql_trees_2 = pd.read_json(soql_url_2)

soql_trees_2

   health  steward  count_tree_id
0    Fair     1or2          21902
1    Fair     3or4           2830
2    Fair  4orMore            200
3    Fair     None          71572
4    Good     1or2         115372
5    Good     3or4          15606
6    Good  4orMore           1361
7    Good     None         396511
8    Poor     1or2           6283
9    Poor     3or4            747
10   Poor  4orMore             49
11   Poor     None          19739
12    NaN     None              1
13    NaN      NaN          31615